### ISSUE TITLE
Pre-wired CBR configuration for fs cloud

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#222]
### Description

Add a submodule (under fscloud directory to follow conventions created from other module) that utilize the submodule https://github.com/terraform-ibm-modules/terraform-ibm-cbr/tree/main/cbr-service-profile to create pre-defined CBR rules needed by the services specified in the FsCloud architecture patterns :
COS -> KMS
Block storage -> KMS
ROKS -> KMS
Activity Tracker route -> COS
VPCs -> container registry
VPCs -> where clusters are deployed -> COS

**Comment by vburckhardt** [comment]
One addition to this ticket is to enable consumers to add their own CBR config in addition to the pre-wired IBM config as an input to the module. Conceptually similar to what is being done with the security group and network acl (eg: https://github.com/terraform-ibm-modules/terraform-ibm-security-group/blob/f7f824c784e85d3c5138a1b894e414a4e7b2de44/main.tf#L179C102-L179C102 )

**Comment by vburckhardt** [comment]
Potential list of input variables:
```
configure_cos_to_kms = true|false (default - true)
configure_block_storage _to_kms = true|false (default - true)
configure_....
zone_vpc_crn_lists = [...]
(...)
customer_cbr_config = {} (see / investigate whether this object is going to become too big / unmaintainable )
```

**Comment by vburckhardt** [comment]
On the customer_cbr_config point from previous comment - I think we should extend the capabilities of the fscloud submodule in the PR https://github.com/terraform-ibm-modules/terraform-ibm-cbr/pull/262 as follows.

1. Create CBR zones (optionally - if CBR zone ids is not passed as input):
    - One zone per service (supporting CBR)
    - One zone for all VPC passed as input
    - One zone for addresses passed as input
 2. Create default CBR rules for each service:
    - Blocking traffic on all endpoints (deny all by default). ( Note that there is a limitation in CBR preventing from setting an explicit deny – proposal is to set an allow list based on a non-routable IP – eg: 1.1.1.1 which effectively prevents traffic from all source – except 1.1.1.1 – this dummy source could be made configurable as input of the module) - we can reserve this for a subsequent PR.
    - Open traffic for known necessary fscloud flows (this is done in the PR already)
         - COS -> KMS
         - Block storage -> KMS
         - ROKS -> KMS
         - Activity Tracker route -> COS (pending addition of AT as zone)
         - VPCs -> container registry
         - VPCs -> where clusters are deployed -> COS
    - Append custom CBR rule context (passed as input) to the default CBR rules - this was the open question in previous comment on how we shape this (customer_cbr_config )

Interface:
Inputs:
- List of ids of VPCs that participate in the fscloud topology ( this is zone_vpc_crn_lists )
- Custom rules to add. Map of: 
       - service-name -> ( rule context definition )
       - This is a new input to the fscloud module
- Map of existing zone Ids (if passed, then the module does not create those zones, and use the passed zone id) - this is a new input
      - service-name -> zoneId
      - Vpc context zoneId
      - List of address zoneIds

Outputs - new outputs
- A map of service zones – (servicename, zoneId)
- A map of rules – (servicename , ruleId)

*"servicename" above is the string that is used in CBR to represent a service

Limitations considered in the design:
- A service can be targeted by only one CBR rule in a given account
- Terraform provider does not allow editing existing rule created through some other process / including other terraform logic - so need a mechanism built in the module to create and handle updates of zone, including updating zone rule definitin.

**Comment by vburckhardt** [comment]
Started going in the direction of https://github.com/terraform-ibm-modules/terraform-ibm-cbr/issues/222#issuecomment-1643783153 in this branch https://github.com/terraform-ibm-modules/terraform-ibm-cbr/tree/pre-wired-cbr-ext

**Comment by ocofaigh** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-cbr/pull/267 is merged - closing
