### ISSUE TITLE
Adjust cardinality of zone creation cbr-service-profile

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#259]
### Description

Based on early consumer inputs on the cbr-service-profile, it would be desirable to create one zone per service, as opposed to grouping multiple services in one zone.

Concretely, taking the existing example at https://github.com/terraform-ibm-modules/terraform-ibm-cbr/blob/99b9fe8a581a01509d8b32dcf8319e306cdaf664/examples/multi-service-profile/variables.tf#L40 - this results in creating one service zone with "directlink", "is" as services source. Instead, the desire is to create 2 CBR zones - one zone with is, and one zone with direct link.

**Comment by vburckhardt** [comment]
@Ak-sky - fya - this is related to https://github.com/terraform-ibm-modules/terraform-ibm-cbr/issues/222

**Comment by Ak-sky** [comment]
> @Ak-sky - fya - this is related to #222

Sure @vburckhardt, will work on this.

**Comment by vburckhardt** [comment]
Part of the logic in https://github.com/terraform-ibm-modules/terraform-ibm-cbr/pull/267

**Comment by ocofaigh** [comment]
PR merged - closing
