### ISSUE TITLE
Give ability to skip specific service zone creation (fscloud profile module)

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#269]
### Description

Add some logic to allow consumer to indicate how to skip creation of some rules. Currently the module creates rule for all services in https://github.com/terraform-ibm-modules/terraform-ibm-cbr/pull/267

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Ak-sky** [comment]
PR merged, closing this.
Included in https://github.com/terraform-ibm-modules/terraform-ibm-cbr/releases/tag/v1.7.0
