### ISSUE TITLE
give full flexibility on cbr rule and zone names in fscloud submodule

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#279]
### Description

Feedback from one consumer. Currently flexibility is on the prefix only.

This should be an optional name in the inputs of the module per zone, rule - current support with prefix should remain as well.

**Comment by Khuzaima05** [comment]
@vburckhardt
Could you please explain `optional name in the inputs`, Do we have to add new variable for the name?

**Comment by ocofaigh** [comment]
@Khuzaima05 The module needs to have the ability for the consumers to either:

a) pass a prefix which will be used as part of the naming (currently already supported)
OR
b) using new optional variables, consumers can control the exact naming of resources

**Comment by vburckhardt** [comment]
fixed in https://github.com/terraform-ibm-modules/terraform-ibm-cbr/pull/313
