### ISSUE TITLE
fscloud: add kube -> IS flow in pre-wired rules

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#290]
### Description

Needed to enable the iks stack to create things that vpc lb.

**Comment by Ak-sky** [comment]
Hi @vburckhardt, do we need to have a allow variable and add this as an optional?

**Comment by Ak-sky** [comment]
Included in https://github.com/terraform-ibm-modules/terraform-ibm-cbr/releases/tag/v1.14.0, closing this.
