### ISSUE TITLE
fscloud: is -> cos is missing?

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#292]
Error in logs:
	Failed to write Flow Log file for the past 24 hours. Dropping flow log for Virtual Server ...

Flow logs writes to COS. Suggest to try adding is-> cos flow in the rule and see if reproducable.

**Comment by Ak-sky** [comment]
Hi @vburckhardt, which log file we are referring here?

**Comment by vburckhardt** [comment]
Activity Tracker logs

**Comment by Ak-sky** [comment]
and do we need to have a allow variable for this?

**Comment by vburckhardt** [comment]
Yes, I'd suggest so, from a consistency perspective
