### ISSUE TITLE
Remove public default context set to 1.1.1.1

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#349]
### Description

This should not longer be needed to force the implicit deny all on an interface. All Cloud services now have this implicit deny.
This context is also being flagged up by SCC in recent release, creating some noise in audit reports.

**Comment by vburckhardt** [comment]
I had a chat with the roks team - the limitation https://cloud.ibm.com/docs/containers?topic=containers-cbr&interface=ui#cbr-limitations has been removed so we should be able to proceed.

**Comment by Ak-sky** [comment]
Available in release https://github.com/terraform-ibm-modules/terraform-ibm-cbr/releases/tag/v1.20.0, closing this.
