### ISSUE TITLE
pre-wired rule for cos (private endpoint)

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#362]
Currently:

    "cloud-object-storage" : [{
      endpointType : "direct",
      networkZoneIds : flatten([
        var.allow_vpcs_to_cos ? [local.cbr_zone_vpcs.zone_id] : [],
        var.allow_at_to_cos ? [local.logdnaat_cbr_zone_id] : [],
        var.allow_is_to_cos ? [local.is_cbr_zone_id] : []
      ])

However, AT and IS would access COS through the private endpoint - so there should be an update to have the private endpoint for at and is. direct should only be for VPC.

**Comment by ocofaigh** [comment]
@vburckhardt There is no private VPE for COS in VPC land. They only support direct

**Comment by Ak-sky** [comment]
Available in release https://github.com/terraform-ibm-modules/terraform-ibm-cbr/releases/tag/v1.22.1, closing this.
