### ISSUE TITLE
Add messagehub -> kms in prewired

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#404]
### Description

Currently missing from https://github.com/terraform-ibm-modules/terraform-ibm-cbr/blob/ecacb5753fff540d28114ab0aae7b8b2b116c1a6/modules/fscloud/main.tf#L221

**Comment by Ak-sky** [comment]
Released in https://github.com/terraform-ibm-modules/terraform-ibm-cbr/releases/tag/v1.19.0, closing this.
