### ISSUE TITLE
Support Terraform 1.8

### ISSUE THREAD

**Issue by unblu-inc** [terraform-ibm-modules/terraform-ibm-cbr#455]
### Description

You restrict the Terraform version to `">= 1.3.0, <1.7.0"` in `version.tf`. Is there a good reason for it? If not, can you allow 1.8?

**Comment by unblu-inc** [comment]
BTW: 1.7 is also not allowed:

```
╷
│ Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/cbr_fscloud/modules/cbr-rule-module/version.tf line 2, in terraform:
│    2:   required_version = ">= 1.3.0, <1.7.0"
│ 
│ Module module.cbr_fscloud.module.cbr_rule (from ../../modules/cbr-rule-module) does not support Terraform version 1.7.5. To proceed, either choose another
│ supported Terraform version or update this version constraint. Version constraints are normally set for good reason, so updating the constraint may lead
│ to other errors or unexpected behavior.
╵
```

**Comment by ocofaigh** [comment]
@unblu-inc We had it restricted to only allow versions that IBM Cloud Schematics supported. However we are more than likely going to be removing the upper limit here across all of our modules so please bare with us while we make a final decision and start rolling that out

**Comment by gysel** [comment]
Excellent, thanks! (I created the this issue but had the wrong account active when I did so ;) )

**Comment by ocofaigh** [comment]
@gysel Upper range constraints have been removed in https://github.com/terraform-ibm-modules/terraform-ibm-cbr/releases/tag/v1.22.2
