### ISSUE TITLE
IAM is not a valid service name

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#479]
https://github.com/terraform-ibm-modules/terraform-ibm-cbr/blob/e6e1e54d7c12a6354a844c35f9ec7774bb527afa/modules/fscloud/main.tf#L99

only service-group-id should be specified when the pseudo service IAM is used.

Error: CreateRuleWithContext failed The resource attribute `serviceName`'s value 'IAM' is invalid.

**Comment by Ak-sky** [comment]
Available in release https://github.com/terraform-ibm-modules/terraform-ibm-cbr/releases/tag/v1.23.2, closing this.
