### ISSUE TITLE
Add MQ dataplan segmentation

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#480]
Similar to ICD services - see
https://github.com/terraform-ibm-modules/terraform-ibm-cbr/blob/e6e1e54d7c12a6354a844c35f9ec7774bb527afa/modules/fscloud/main.tf#L335

**Comment by Ak-sky** [comment]
Available in https://github.com/terraform-ibm-modules/terraform-ibm-cbr/releases/tag/v1.23.1, closing this.
