### ISSUE TITLE
global_deny should be documented explicitly

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#481]
https://github.com/terraform-ibm-modules/terraform-ibm-cbr/blob/e6e1e54d7c12a6354a844c35f9ec7774bb527afa/modules/fscloud/variables.tf#L204

Indicate the effect of global_deny explicit in the fscloud doc + mention it in the associated example (where global_deny is set to false for some services, when it is actually already false by default, adding to the confusion)

**Comment by Ak-sky** [comment]
PR merged, closing this.
