### ISSUE TITLE
event notification changed possible enforcement modes

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#482]
"event-notifications" : {

      "enforcement_mode" : "report"

    },

"message": "The rule enforcement mode 'report' is not supported for service 'event-notifications' and API types 'all'. Valid values are: disabled, enabled",

**Comment by vburckhardt** [comment]
Could we also see if there is a recent change in this area on the backend? I suspect this issue would have been caught through the automated tests when checking in the change.

**Comment by ocofaigh** [comment]
@Ak-sky This is the same as https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/issues/250 right?

**Comment by Ak-sky** [comment]
> @Ak-sky This is the same as [terraform-ibm-modules/terraform-ibm-event-notifications#250](https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/issues/250) right?

Yes, this is same.
 - This was due to the recent addition of EN SMTP API which does not support report mode.
 - As we are restricting all the Service API of the service, SMTP API also comes under it.

**Comment by ocofaigh** [comment]
So @Ak-sky do we need to take some action in CBR module too?

**Comment by Ak-sky** [comment]
Available in https://github.com/terraform-ibm-modules/terraform-ibm-cbr/releases/tag/v1.23.1, closing this.
