### ISSUE TITLE
global_deny_target_service_details potentially missing consumer customizations

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#483]
https://github.com/terraform-ibm-modules/terraform-ibm-cbr/blob/e6e1e54d7c12a6354a844c35f9ec7774bb527afa/modules/fscloud/main.tf#L288

var.target_service_details should likely be replaced with local.target_service_details which contains the merge / override from the consumer customizations.

**Comment by imprateeksh** [comment]
[PR](https://github.com/terraform-ibm-modules/terraform-ibm-cbr/pull/489) merged hence closing the issue.

**Comment by Ak-sky** [comment]
Available in release https://github.com/terraform-ibm-modules/terraform-ibm-cbr/releases/tag/v1.23.3.
