### ISSUE TITLE
add cloud log

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cbr#567]
### Description

https://github.com/terraform-ibm-modules/terraform-ibm-cbr/blob/93ea730d53e26591eeaa8408a4d1fd3dc8d3e50a/modules/fscloud/main.tf#L122

```
"logs" : {

      "enforcement_mode" : "report"

    }
```

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by arya-girish-k** [comment]
Merged the PR : https://github.com/terraform-ibm-modules/terraform-ibm-cbr/pull/568 
Closing this issue
